### ISSUE TITLE
Fiscal year fields not calculating correctly

### ISSUE THREAD

**Issue by backofficeteam** [progressivetech/net.ourpowerbase.sumfields#108]
Testing on Civi demo site, Civi 5.79.alpha1, Summary Fields v.5.0.3

I set the fiscal year to start 1 July.  Here are the sample donations on the demo user's record:

![image](https://github.com/user-attachments/assets/d1be5611-e678-4d01-9a41-edf7a0dc4a81)

By my calculation, their current FY (1 July 2024-30 June 2025) donation total should be $1, their previous FY (1 July 2023-30 June 2024) donation total should be $5.55, and their FY before last (1 July 2022-30 June 2023) total should be $4.55.  However, this is what Summary Fields reports:

![image](https://github.com/user-attachments/assets/cba31c53-d673-47df-9ece-0f1e060304d6)

**Comment by jmcclelland** [comment]
Which Demo did you use? By default, in CiviCRM, the fiscal year starts on January 1 (and those summary fields appear to have been calculated based on a January 1 start of the fiscal year, not a July 1 start). You can check the fiscal year start via `Administer -> Localization -> Date Formats`.

If you change the fiscal year, you have to re-save the summary fields configuration to re-generate the totals.

Let me know if that resolves the issue!

jamie

**Comment by backofficeteam** [comment]
I was using dmaster.demo.civicrm.org. And yes, I was aware where to check the fiscal year start, but it was not clear that the summary fields config needed to be updated to pick up the correct FY - thanks for the clarification.  Confirming that worked.
