### ISSUE TITLE
Can remove some settings cruft

### ISSUE THREAD

**Issue by eileenmcnaughton** [progressivetech/net.ourpowerbase.sumfields#21]
There is if (version > 4.7. alpha) around the use of the api to create settings - but that api call has worked since 4.2. It's only the other methodology that has changed. The settings api calls will work for $config and settings on all versions. It's only the other functions that have changed over time

**Comment by jmcclelland** [comment]
Thanks Eileen. Are you referring to the sumfields_save_setting/sumfields_get_setting functions?

In both cases I'm using the API, but pre 4.7 I think I need the group_name for it to work (whereas after 4.7, group_name was removed so we'll get an error).

Or is there a different place you are referring to?

**Comment by eileenmcnaughton** [comment]
the group name should not be required pre 4.7 for the api calls - it was always optional

**Comment by jmcclelland** [comment]
cruft is removed.
