### ISSUE TITLE
Make translation function available

### ISSUE THREAD

**Issue by Fabian-SYSTOPIA** [progressivetech/net.ourpowerbase.sumfields#28]
Quite a while ago you guys added the function to make the extensions strings translatable to other languages (see [this commit](https://github.com/progressivetech/net.ourpowerbase.sumfields/commit/d099a3ba796e18662cbbfe71f4c3476eb5496655)). 

However, I realised that after a fresh install on 4.7.27 the translated strings do not seem to have any effect. Is there anything I would need to do to disply the translated strings (except for having the proper CiviCRM system language set)? Or is there a problem with the extensions translation function and could you maybe fix it? 

Once that's done I would be very happy to provide you with updates German translations for all strings.

**Comment by Fabian-SYSTOPIA** [comment]
Any news on this? Would be really great if you could let me know if teher are any plans to do this in the future, otherwise I will start translating manually for all our client's intsallations.

**Comment by jmcclelland** [comment]
Sorry for the silence on this issue - just to say that it's not intentional, I just haven't had a chance to review what is wrong. I'm open any pull requests or tips on what the problem is.

**Comment by Fabian-SYSTOPIA** [comment]
Unfortunately I am not a developer so I do not really know, what the technical issue is. Will try and ask if someone  from our team with IT skills can look into this.

**Comment by jmcclelland** [comment]
I've created a de_DE/LC_MESSAGES directory in l10n and now german (that is translated) should be showing. This will be available in the next release.
