### ISSUE TITLE
SummaryFields on large scale site installations

### ISSUE THREAD

**Issue by VangelisP** [progressivetech/net.ourpowerbase.sumfields#29]
On large scale sites and under specific circumstances, MySQL triggers are causing slowdown to importation/exportation functions of eg. Contributions.

I made a PR that adds an option in the settings that allows users to select how SummaryFields works.

* Default - The way so far
* Remove triggers - Calculations are based on CiviCRM Cron jobs and when they run.

Technically, once the option is selected, I am always forcing the scheduled job to be re-scheduled upon completion.
Also, I am intercepting the trigger rebuild function and if the option is '**remove triggers**', i'm just bailing out.

One important thing is that the scheduled job SumFields.Gendata should be run on each cron.

I've tested this modification on 2 big clients and looks good.

**Comment by VangelisP** [comment]
Hello @jmcclelland , is there a plan for a new SummaryFields release tag now that the new changes are being merged?

**Comment by jmcclelland** [comment]
Thanks for the nudge.  I found [one more small bug](https://github.com/progressivetech/net.ourpowerbase.sumfields/commit/0d5db915c2ad8f9a777b212257635391d05b2a43) and have now just tagged a new release. It should show up in CiviCRM's extension repo tomorrow.
