### ISSUE TITLE
Adding Fields for Current and Previous Financial Year (Apr-Mar and also Jul-)Jun

### ISSUE THREAD

**Issue by petednz** [progressivetech/net.ourpowerbase.sumfields#34]
Hi - we had to do some work for client to let them see Current and Previous Financial year - their Financial Year ran 1 April - 31 March

While we were doing that we thought we might as well cover the other most likely FY ie 1 July - 30 June.

Would you be interested in this as a PR?

**Comment by jmcclelland** [comment]
Hi Peter - The current/previous year totals should be respecting the Fiscal year start date set by CiviCRM (Administer -> Localization -> Date Format).

Is that what you mean? (or maybe that is not working properly?)

**Comment by petednz** [comment]
Or maybe it just eluded us. I did not know that setting existed, or actually I probably did once upon a time. Perhaps we could provide a PR to add 'Financial' to 'current year', and to add in the help text "Financial year needs to be set in Administer -> Localization -> Date Format?

**Comment by jmcclelland** [comment]
Yes - that would be great.

**Comment by jmcclelland** [comment]
Thanks for the improvement. merged!
