### ISSUE TITLE
4.6 - Advanced Search with Summary Fields Not Working

### ISSUE THREAD

**Issue by Cullpepper** [progressivetech/net.ourpowerbase.sumfields#4]
Hi there,

Love this extension but something seems wrong in civi 4.6.6 (running drupal 7).

Summary fields are calculated and display correctly. Searches made in "Advanced Search" using a summary field as a qualifier display all contacts, regardless of the value.

**Comment by jmcclelland** [comment]
Thanks for the report. I'm having a hard time replicating it. Can you provide a more concrete example (e.g. which field are you searching on and what values are you putting in the advanced search box)? Also, when you say "all contacts" do you mean all contacts in your database or all contacts with a value in the field you are searching?

**Comment by Cullpepper** [comment]
Hi there- I'll try to detail my installation and exact example. 

Installation:
Drupal 7.31
Civicrm 4.6.6
Host: mediatemple
Php: 5.3
Extension: Summary Fields 2.0.3

Example:

Summary Fields are enabled and show correctly for contacts. They also appear as an additional search (accordion) tab in reports and advanced search. 

Issues: 
* Advanced searches using any "summary field" as the search criteria return *all* contacts.
* Specific example: Advanced Search seeking "Total Lifetime Contributions" from 100 to 500 returns all contacts. 
* Second Example: Advanced Search seeking "Count of Contributions" from 5 to 10 returns all contacts.
* Reports: In Constituent Report, "summary fields" appear as a filter criteria. Adding any "summary field" or combination of summary fields does not affect the report.

To answer your question above, when I say "all contacts" I mean all contacts in the database. It's as though the search criteria (or filter criteria) are not counted if they are a summary field. 

Other information:

"Search Builder" seems to work correctly. A Search Builder query of Count of Contributions > N returns correct results. 

Please let me know if you'd like screenshots or other debugging output.

**Comment by jmcclelland** [comment]
Thanks for the complete info. Very strange, especially since search builder works.

Can you login to your database directly (like from phpMyAdmin or from the command line) and run a DESC table statement against the custom table summary fields generated?

I'm curious to see if you have the same table types.

Here's an example of me doing it on a working site:

```
mysql> desc civicrm_value_summary_fields_51;
+--------------------------------------+------------------+------+-----+---------+----------------+
| Field                                | Type             | Null | Key | Default | Extra          |
+--------------------------------------+------------------+------+-----+---------+----------------+
| id                                   | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| entity_id                            | int(10) unsigned | NO   | UNI | NULL    |                |
| total_lifetime_contributions_476     | decimal(20,2)    | YES  | MUL | NULL    |                |
| total_contributions_this_year_477    | decimal(20,2)    | YES  | MUL | NULL    |                |
| total_contributions_last_year_478    | decimal(20,2)    | YES  | MUL | NULL    |                |
| amount_of_last_contribution_479      | decimal(20,2)    | YES  | MUL | NULL    |                |
| date_of_last_contribution_480        | datetime         | YES  | MUL | NULL    |                |
| date_of_first_contribution_481       | datetime         | YES  | MUL | NULL    |                |
| largest_contribution_482             | decimal(20,2)    | YES  | MUL | NULL    |                |
| count_of_contributions_483           | int(11)          | YES  | MUL | NULL    |                |
| average_annual_calendar_year_con_484 | decimal(20,2)    | YES  | MUL | NULL    |                |
| date_of_last_membership_payment_485  | datetime         | YES  | MUL | NULL    |                |
| amount_of_last_membership_paymen_486 | decimal(20,2)    | YES  | MUL | NULL    |                |
| name_of_the_last_attended_event_487  | varchar(128)     | YES  | MUL | NULL    |                |
| date_of_the_last_attended_event_488  | datetime         | YES  | MUL | NULL    |                |
| total_deductible_contributions_l_489 | decimal(20,2)    | YES  | MUL | NULL    |                |
| total_deductible_contributions_t_490 | decimal(20,2)    | YES  | MUL | NULL    |                |
| total_contributions_year_before__491 | decimal(20,2)    | YES  | MUL | NULL    |                |
| total_deductible_contributions_y_492 | decimal(20,2)    | YES  | MUL | NULL    |                |
| total_number_of_events_501           | int(11)          | YES  | MUL | NULL    |                |
| number_of_events_attended_502        | int(11)          | YES  | MUL | NULL    |                |
| events_attended_as_percent_of_to_503 | int(11)          | YES  | MUL | NULL    |                |
| number_of_no_show_events_504         | int(11)          | YES  | MUL | NULL    |                |
| no_shows_as_percent_of_total_eve_505 | int(11)          | YES  | MUL | NULL    |                |
+--------------------------------------+------------------+------+-----+---------+----------------+
24 rows in set (0.00 sec)

mysql>
```

**Comment by Cullpepper** [comment]
Sure thing: (see attachment)

thanks,
-Cullen

**Comment by Cullpepper** [comment]
Found the issue- there's a drupal module/civi extension called "pogstone"
that is a conflict.

Disabling the extension and drupal module allows Summary fields to work
correctly in all the areas I listed before.

Sheesh. Sorry.

**Comment by jmcclelland** [comment]
Thanks for the update! Which extension is is? Probably a good idea to post an issue for it - if you haven't already.
