### ISSUE TITLE
Clearing out clutter when detailed logging is enabled

### ISSUE THREAD

**Issue by scoobird** [progressivetech/net.ourpowerbase.sumfields#40]
One of our clients loves this extension and also has civicrm database logging on. I've recently had to remove a bunch of entries to log_civicrm_contact and log_civicrm_value_summary_fields_xx that are inserted when the fields were getting recalculated with the cron job. When it was running hourly it really ballooned the size of the log tables. This civi only has 30k contacts in it, and just a few months after we switched the extension to calculate using cron there were millions of log entries. I don't personally find these changelog entries necessary, as the things that are being recalculated (event participation, contributions) are also tracked in the logs, so I've been rather ruthless in deleting records.

I've set the job to run less frequently, but I've been thinking that it may be more sustainable to add a utility that deletes older contact changelog entries automatically and/or on demand from the Summary Fields settings page.

Has this issue come up before? Can you recommend a different solution? And finally, is trimming the change logs something you'd consider incorporating into the extension in some way and if so can I help make that happen?

**Comment by jmcclelland** [comment]
Hi - can you say more about how things are setup with your cron job?  In particular, is the site configured with "How often should summary data be updated?" set to cron job? If so, changing that to instantly might resolve this problem.

Instantly is the default and should result in tables being updated only when data changes. But if you have cron job selected, then everything will get blown away and re-created on every cron run. So, the cron job setting is not a good fit with logging enabled.

I'm also not sure why the `civicrm_contact` table would mushroom in size (although I can understand why the `log_civicrm_value_summary_fields_xx` would). To address `log_civicrm_value_summary_fields_xx`, I wonder if we should add a [alterLogTables](https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_alterLogTables/) hook that simply excludes the summary fields table from logging. I'm curious if this log table accurately records who made the change? I'm not exactly how triggers interact with the civicrm logging feature.

**Comment by jmcclelland** [comment]
I think adding an option to exclude log tables would be a good move. And adding text to the update timing option warning people about performance problems if you don't exclude tables. Open to a PR request on one or both! but probably won't have time to implement this myself.

**Comment by jmcclelland** [comment]
It looks like you found a very simple and elegant solution - no need for settings or anything. Does your PR fully address this issue?

**Comment by scoobird** [comment]
Yep! this will solve the issue quietly. After thinking on it for a while, adding a setting to store this extraneous data for the presumably few sites using logging seemed unnecessary.

**Comment by jmcclelland** [comment]
Excellent! Thank you!
