### ISSUE TITLE
All civic menus broken, they don't show.  Error Class 'E' not found in sumfields.php on line 29

### ISSUE THREAD

**Issue by Paul-Tahoe** [progressivetech/net.ourpowerbase.sumfields#44]
I'm testing an upgrade in a test db and saw an update to summary fields.  Sorry it bombs.  

Here's the code, line 29 is the one starting with label

function sumfields_civicrm_navigationMenu(&$menu) {
  $path = "Administer/Customize Data and Screens";
  _sumfields_civix_insert_navigation_menu($menu, $path, array(
    'label' => E::ts('Summary Fields'),
    'name' => 'Summary Fields',
    'url' => 'civicrm/admin/setting/sumfields',
    'permission' => 'administer CiviCRM',
    'operator' => '',
    'separator' => '0'
  ));

In the test db I put that back to what it was.

    'label' => ts('Summary Fields', array('net.ourpowerbase.sumfields')),

which fixed though, I'm not sure if maybe there was suppose to be some change to this line

**Comment by wafuce** [comment]
Hello, thank you Paul, I did try you fix. Great !
I used net.ourpowerbase.sumfields in a production site… 
All menus were indeed broken both on Drupal & and Drupal 8.

**Comment by fulltrucker** [comment]
We had a client hit the upgrade button on the Summary Fields extension, and like @Paul-Tahoe the CiviCRM admin menu disappeared. I disabled the extension, and it came back. I tried to re-enable the extension and got the following error:

`Fatal error: Class 'E' not found in /var/www/chorusamerica.org/htdocs/sites/default/files/civicrm/ext/net.ourpowerbase.sumfields/sumfields.php on line 60`

I see that class E is defined in several spots/files, but not knowing how it should properly be used I have no fix. Just wanted to document a similar symptom/issue in hopes this will be addressed. For now I will likely roll the client back to v3.1.3.

**Comment by themak1985** [comment]
Same issue here:

Upgraded to 4.0 - database upgrades never fully executed, just hanged - menu disappeared - disabled extension - menu returned - re-enabled extension - get this error.

`Notice: Undefined index: type in CRM_Core_BAO_Setting::validateSetting() (line 294 of /home/columbiaccs/www/www/sites/all/modules/civicrm/CRM/Core/BAO/Setting.php).
Notice: Undefined index: type in CRM_Core_BAO_Setting::validateSetting() (line 294 of /home/columbiaccs/www/www/sites/all/modules/civicrm/CRM/Core/BAO/Setting.php).
Notice: Undefined index: type in CRM_Core_BAO_Setting::validateSetting() (line 294 of /home/columbiaccs/www/www/sites/all/modules/civicrm/CRM/Core/BAO/Setting.php).
Notice: Undefined index: type in CRM_Core_BAO_Setting::validateSetting() (line 294 of /home/columbiaccs/www/www/sites/all/modules/civicrm/CRM/Core/BAO/Setting.php).
Notice: Undefined index: type in CRM_Core_BAO_Setting::validateSetting() (line 294 of /home/columbiaccs/www/www/sites/all/modules/civicrm/CRM/Core/BAO/Setting.php).
Notice: Undefined index: type in CRM_Core_BAO_Setting::validateSetting() (line 294 of /home/columbiaccs/www/www/sites/all/modules/civicrm/CRM/Core/BAO/Setting.php).
Error: Class 'E' not found in sumfields_civicrm_enable() (line 60 of /home/columbiaccs/www/www/sites/default/files/civicrm/ext/net.ourpowerbase.sumfields/sumfields.php).`

**Comment by jmcclelland** [comment]
I'm so sorry! Thanks everyone for the feedback. I've fixed the problem and version 4.0.1 should come out overnight.

The easiest quick fix is to add the following line to sumfields.php

```
--- a/sumfields.php
+++ b/sumfields.php
@@ -1,6 +1,7 @@
 <?php
 
 require_once 'sumfields.civix.php';
+use CRM_Myextension_ExtensionUtil as E;
```

**Comment by Paul-Tahoe** [comment]
Can you somehow unrelease version 4.0 so that it doesn't show in peoples manage extension pages as there being an upgrade available?  Sadly, some people blindly hit the upgrade button without testing first in a test env.

**Comment by Paul-Tahoe** [comment]
Oh and thank you for fixing this and the other fixes/additions that are in 4.0.

**Comment by jmcclelland** [comment]
Unfortunately, I'm not sure how to do that :(. But... the new release is out so hopefully this is now behind us.

**Comment by jmcclelland** [comment]
Unfortunately, still broken: https://github.com/progressivetech/net.ourpowerbase.sumfields/issues/45

Current version (4.0.2) should work properly.
