### ISSUE TITLE
Unable to disable extension on Drupal Civicrm 5.10

### ISSUE THREAD

**Issue by eudaimonstro** [progressivetech/net.ourpowerbase.sumfields#46]
When using the GUI: 
![image](https://user-images.githubusercontent.com/5083012/52671872-182aa000-2ed1-11e9-8661-05a44dc9a819.png)

When using drush:
`drush ced net.ourpowerbase.sumfields`
`WD php: Error: Class 'CRM_Myextension_ExtensionUtil' not found in sumfields_delete_custom_fields_and_table() (line 698 of                         [error]
/opt/bitnami/apps/civicrm/htdocs/sites/default/files/civicrm/ext/net.ourpowerbase.sumfields/sumfields.php).
Error: Class &#039;CRM_Myextension_ExtensionUtil&#039; not found in sumfields_delete_custom_fields_and_table() (line 698 of /opt/bitnami/apps/civicrm/htdocs/sites/default/files/civicrm/ext/net.ourpowerbase.sumfields/sumfields.php).
Drush command terminated abnormally due to an unrecoverable error.`

**Comment by Paul-Tahoe** [comment]
You must likely have version 4.0.1, check the sumfields.php.  If the 3rd line is 
use CRM_Myextension_ExtensionUtil as E;
You have a bad version.  There is a fix in 4.0.2.  Unfortunately, for some reason that doesn't come up as an upgrade within civi yet.  It is correct here in github.  

You can change it to 

use CRM_Sumfields_ExtensionUtil as E;

as it should work.

**Comment by jmcclelland** [comment]
Thanks @Paul-Tahoe  - that says it all.
