### ISSUE TITLE
Unable to update summary fields

### ISSUE THREAD

**Issue by logofakt** [progressivetech/net.ourpowerbase.sumfields#6]
Hi Jamie,

on Drupal 7.x I'm running a CiviCRM version 4.5.8 and 4.6.11. On both I updated Summary Fields. Unfortunately the fields I selected are not calculated / recalculated. Instead I get an error:

"Failed to get the custom groups parameters
Can't add new fields"

The actual log is attached.

What I've done by now: 
Recreated the desired fields in aministration | data and views | summary fields which caused the error above
Execute the job manualy which leads to the log entry shown in the attached pdf file
Deactivated the extension, deinstalled it, installed it again and activated it, looked for user's rights
Going again thru the two steps above
Nothing did help.

I like your extension very much so I hope you will help me to get over this issue.

Regards
Christian Lauer

[19-01-2016 23-11-26.pdf](https://github.com/progressivetech/net.ourpowerbase.sumfields/files/97540/19-01-2016.23-11-26.pdf)

**Comment by jmcclelland** [comment]
Hi Christian,

The sumfields extension should automatically create the custom data group and fields (and remove them when uninstalled) - so you should never need to manually create them yourself. 

Once the extension creates the custom data table, it records the custom data group id in a setting variable.

Whenever you adjust your settings (to change which summary fields you want - or the first time you generate your fields), sumfields will try to retrieve this custom data group id. If it is not able to properly retrieve this id, then you will get the message you are reporting.

Therefore... I suspect that something is doing wrong at installation time.

I would suggest:

 * Disable and Remove the extension.
 * Manually delete any custom data groups and fields that are left behind
 * Re-install and pay close attention to any errors during installation
 * Check for the creation of the table via the Administration link (should be called "Summary Fields")
 * If the custom data group is not there, check the ConfigAndLog file for any errors

**Comment by logofakt** [comment]
Hi Jamie,

thanks for your help, it works.
