### ISSUE TITLE
triggers settings not enabled

### ISSUE THREAD

**Issue by twomice** [progressivetech/net.ourpowerbase.sumfields#83]
As described at https://civicrm.stackexchange.com/q/35581/907

I'm seeing similar behavior to that reported in the SE question above. Summary Fields configuration page reports this, even after rebuilding triggers with `civicrm/menu/rebuild&reset=1&triggerRebuild=1`
![sK1gl](https://user-images.githubusercontent.com/759449/104652743-35e57e80-567f-11eb-8149-a2617b757926.png)

This seems to indicate that triggers are not in place, and therefore real-time update of configured summary fields will not be happening, even though the cron job may be doing periodic updates.

**Comment by jmcclelland** [comment]
Are you running the latest release or the latest version in github? If you are not running the latest version in github - would you mind upgrading and letting me know if that fixes the probe?

I also did more of a follow up on the SE question here: https://civicrm.stackexchange.com/questions/35581/summary-fields-triggers-settings-not-enabled/38613#38613

The SE answer provides a work-around and some helpful user info on how to debug. But... if you find that upgrading to the github version automatically solves the problem then I'll definitely release a new version.

**Comment by andyburnsco** [comment]
I'm on version 5.0.0 and did the steps described here https://civicrm.stackexchange.com/questions/35581/summary-fields-triggers-settings-not-enabled/38613#38613. The "Status of current settings" and "Data update method: Cron Job" are now correct but no triggers exist for civicrm_contribution or Triggers for civicrm_participant.

![image](https://user-images.githubusercontent.com/18341942/115869266-a41ea780-a40b-11eb-934c-541174884e66.png)


The Scheduled job says e.g. `Finished execution of Call SumFields.Gendata API with result: Success (a:1:{i:0;s:89:"Original Status: scheduled:2021-04-23 06:32:07, New Status: scheduled:2021-04-23 07:47:03";})
`
![image](https://user-images.githubusercontent.com/18341942/115869411-d9c39080-a40b-11eb-92be-85226f5a1dec.png)

Separately, what are the findings of this extension on a large db of around 800K records? I've been very selective and using the simplified fields for performance considerations.

**Comment by jmcclelland** [comment]
Hi @andyburnsco  - you have a choice of update methods - either "Instantly" or "When the cron job runs"

If you choose "Instantly", then triggers will be added and the second a new contribution is added to your database, the triggers will update the summary fields.

However, you seem to have chosen to run on the cron job - which is why the triggers are not enabled, so that's to be expected.

As for the performance question, if you mean 800K contributions, it should be fine. If you mean 800K contacts, then it's more then I have any real experience with!

**Comment by jmcclelland** [comment]
I'm going to close this as fixed, but please let me know if there are still any outstanding aspects to the issue.
